### ISSUE TITLE
3D Kernels 

### ISSUE THREAD

**Issue by jaysnanavati** [shiba24/3d-unet#5]
Hi - I am trying to understand the kernels used for the convolution here, its quite unclear from the paper and the source. Would greatly appreciate it if you could perhaps shed some light on this.

Thanks  :)

**Comment by shiba24** [comment]
Hi @jaysnanavati , please see https://github.com/shiba24/3d-unet/blob/master/chainer/u_net_3d.py . The parameters are : ConvolutionND(ndim, in_channels, out_channels, ksize, stride=1, pad=0, nobias=False, initialW=None, initial_bias=None, cover_all=False)
